### PR TITLE
feat: add queryStatisticsCollectionForQuantity API

### PR DESCRIPTION
**Pull request by taisuke-j**
## Summary

Added `queryStatisticsCollectionForQuantity` method, which internally calls **HKStatisticsCollectionQuery** on the native side.
> **A query that performs multiple statistics queries over a series of fixed-length time intervals.**
- https://developer.apple.com/documentation/healthkit/hkstatisticscollectionquery
- https://developer.apple.com/documentation/healthkit/queries/executing_statistics_collection_queries

@robertherber One quick question. You want to call this `queryStatisticsCollectionForQuantity` not `queryStatisticsCollection` etc, because there is already a method called `queryStatisticsForQuantity` right?

**DAILY STATISTICS FOR STEPCOUNT button**: Added "DAILY STATISTICS FOR STEPCOUNT" button, as shown below, to test the `queryStatisticsCollectionForQuantity` API

a

### Logs after DAILY STATISTICS FOR STEPCOUNT is pressed

```bash
# const now = new Date()
# const startDate = dayjs(now).subtract(5, 'day').toDate()

# const res = await queryStatisticsCollectionForQuantity(
#   HKQuantityTypeIdentifier.stepCount,
#   [HKStatisticsOptions.cumulativeSum],
#   now,
#   { day: 1 },
#   startDate,
#   now,
# )


[
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity": null,
  },
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity":
      {
        "endDate": "2024-10-21T12:32:10Z",
        "quantity": 200,
        "quantityType": "HKQuantityTypeIdentifierStepCount",
        "startDate": "2024-10-20T12:32:10Z",
        "unit": "count",
      },
  },
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity": null,
  },
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity": null,
  },
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity":
      {
        "endDate": "2024-10-24T12:32:10Z",
        "quantity": 1100,
        "quantityType": "HKQuantityTypeIdentifierStepCount",
        "startDate": "2024-10-23T12:32:10Z",
        "unit": "count",
      },
  },
  {
    "averageQuantity": null,
    "duration": null,
    "maximumQuantity": null,
    "minimumQuantity": null,
    "mostRecentQuantity": null,
    "sumQuantity": null,
  }
]
```

### CODE REVIEW

**Comment by robertherber** [comment]
@taisuke-j Could you make sure the lockfile is up to date?

**Comment by taisuke-j** [comment]
@robertherber Updated lockfiles! The EAS build is still in the queue

**Comment by taisuke-j** [comment]
Unfortunately the action timed out. Will you run `eas-ios/eas-build` job at different time of the day? (Bed time for my timezone now)

**Comment by taisuke-j** [comment]
@robertherber I think I need your workflow approval https://github.com/kingstinct/react-native-healthkit/actions/runs/11828343382

**Comment by keigo-taguchi** [comment]
@robertherber
Excited to see this new feature in action! The queryStatisticsCollectionForQuantity API is a game-changer for handling statistics queries with precision and efficiency. Let's get this merged and take our app's capabilities to the next level!

**Review by robertherber — APPROVED** [review]

**Comment by robertherber** [comment]
Released in 8.3.0, thanks @taisuke-j! 🚀

**Comment by arapocket** [comment]
thanks for this

**Pull request merged**
