### PR TITLE
feat: added delete methods for sample

### LINKED ISSUE #29: delete method
I'd love to be able to delete samples in case a user creates on in error. I also don't mind contributing but don't exactly know where to start. Thanks for the great work!

https://developer.apple.com/documentation/healthkit/hkhealthstore/1614155-delete

### PR DESCRIPTION
**Pull request by jonstuebe**
closes #29

### CODE REVIEW

**Comment by robertherber** [comment]
@jonstuebe Could you add an a delete button to the example app so it's possible to try it out as well?

I've made a some refactoring on the TypeScript side which improves typing and DX - sorry that it causes some conflicts. I hope it's not too much of a hassle 👍

**Comment by jonstuebe** [comment]
Didn't mean to close this :( Can you re-open?

**Comment by jonstuebe** [comment]
Got the example added!

**Comment by robertherber** [comment]
Looks great - thanks @jonstuebe! Released in 5.1.0 🚀

One question is whether it's possible to catch delete errors when trying to delete external sources somehow? I've noticed I cannot delete samples coming from my Apple Watch for example - but it seems to just return success for this. I suppose it's the "typical Healthkit behaviour" of failing silently (as when fetching data the user has denied access to) - but maybe there is a way around it?

**Comment by jonstuebe** [comment]
> Looks great - thanks @jonstuebe! Released in 5.1.0 🚀
> 
> One question is whether it's possible to catch errors when trying to delete external sources somehow? I've noticed I cannot delete samples coming from my Apple Watch for example - but it seems to just return success for this. I suppose it's the "typical Healthkit behaviour" of failing silently (as when fetching data the user has denied access to) - but maybe there is a way around it?

Good question. I think you could possible check the metadata of the app and validate if it's the same as the sample that's coming back? 🤔

**Pull request merged**
